keys:
  # Users
  - &users:
    - &byron C946B9667B15865746391841AEBF14525A95C379
  # Hosts
  - &hosts:
    - &itx-nixos age1x9w6endjxpt9jyfjj52tnrs7xg6phf3hys4tdqf565877m2cta3shu2tjt
    - &Byrons-MacBook-Pro age1pe3sdjjmyvu8m9c7as4g2fntrccnzgte9eyhndmrpgx9z4vyvgdqxd5h32
creation_rules:
  - path_regex: hosts/itx-nixos/secrets.ya?ml$
    key_groups:
    - age:
      - *itx-nixos
      pgp:
      - *byron
  - path_regex: hosts/Byrons-MacBook-Pro/secrets.ya?ml$
    key_groups:
    - age:
      - *Byrons-MacBook-Pro
      pgp:
      - *byron
  - path_regex: hosts/secrets.ya?ml$
    key_groups:
    - age:
      - *itx-nixos
      - *Byrons-MacBook-Pro
      pgp:
      - *byron
