keys:
  # Users
  - &users:
    - &byron 2FFDDC00C94F118130ED489208B3ABED7546C580
  # Hosts
  - &hosts:
    - &mynixos age1ssz4a0gyy6vt99cad22pgq9dp888htyplmchry9hc57xy7q4l9gs7lcz7s
creation_rules:
  - path_regex: hosts/mynixos/secrets.ya?ml$
    key_groups:
    - age:
      - *mynixos
      pgp:
      - *byron
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *mynixos
      pgp:
      - *byron
