{
  config,
  lib,
  pkgs,
  ...
}:
let
  keybindings = import ../keybindings.nix { };
  tmux = lib.getExe config.programs.tmux.package;
  zsh = lib.getExe config.programs.zsh.package;
  defaultCommand = "${tmux} new -A -s main; exec ${zsh} -l";

  toLuaString = builtins.toJSON;

  # Kaku 兼容 WezTerm 的 key 命名。这里只把共享按键表中的通用键名
  # 翻译成 Kaku/WezTerm 需要的名字；普通字符键保持原样。
  keyNames = {
    left = "LeftArrow";
    down = "DownArrow";
    up = "UpArrow";
    right = "RightArrow";
    enter = "Enter";
  };

  # 共享按键表使用通用 modifier 名称，适配器负责映射到 Kaku/WezTerm 名称。
  modifierNames = {
    command = "CMD";
    control = "CTRL";
    option = "OPT";
    shift = "SHIFT";
  };
  shiftedKeyNames = {
    "[" = "{";
    "]" = "}";
  };
  toKakuKey =
    shortcut:
    if builtins.hasAttr shortcut.key shiftedKeyNames && builtins.elem "shift" shortcut.modifiers then
      shiftedKeyNames.${shortcut.key}
    else
      keyNames.${shortcut.key} or shortcut.key;
  toKakuMods = modifiers: lib.concatMapStringsSep "|" (modifier: modifierNames.${modifier}) modifiers;

  # 把一条共享 binding 渲染成 Kaku keybinding。
  # Kaku 默认启动 tmux，因此适配器只需要发送 tmux 前缀键和对应 sequence。
  renderBinding =
    binding:
    let
      shortcut = binding.shortcut;
    in
    ''
      table.insert(config.keys, {
        key = ${toLuaString (toKakuKey shortcut)},
        mods = ${toLuaString (toKakuMods shortcut.modifiers)},
        action = wezterm.action.SendString(tmuxPrefix .. ${toLuaString binding.sequence}),
      })
    '';
in
{
  # Kaku 会自己生成和管理 ~/.config/kaku/kaku.lua，这里只生成旁路片段。
  # 在 Kaku 主配置加载完成后手动加入：
  # dofile(os.getenv("HOME") .. "/.config/kaku/tmux-keybindings.lua")(config, wezterm)
  xdg.configFile."kaku/tmux-keybindings.lua".text = ''
    -- Generated by Home Manager. Kaku's main kaku.lua is still managed by Kaku.
    -- Add this after Kaku's bundled config has been loaded:
    -- dofile(os.getenv("HOME") .. "/.config/kaku/tmux-keybindings.lua")(config, wezterm)

    return function(config, wezterm)
      config.keys = config.keys or {}
      config.default_prog = { ${toLuaString zsh}, "-lc", ${toLuaString defaultCommand} }
      local tmuxPrefix = string.char(1)

    ${lib.concatMapStringsSep "\n" renderBinding keybindings.bindings}
    end
  '';
}
